GET http://localhost:3000/friends/
###

GET http://localhost:3000/friends/1/
###

POST http://localhost:3000/friends/
Content-Type: application/json

{
    "id":2,
    "name":"Sir Isac Newton"
}

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